version: '3.8'

services:
  # Servicio de Base de Datos SQL Server
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_buzon
    environment:
      # ¡OJO! Esta contraseña debe ser igual a la que pongas en tu appsettings.json
      SA_PASSWORD: "TuPasswordFuerte123!" 
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql # Para que no se borren los datos al apagar
    networks:
      - buzon-network

  # Servicio de tu API
  api:
    build:
      context: ./Backend/BuzonWeb
      dockerfile: Dockerfile
    container_name: api_buzon
    ports:
      - "5000:8080" # Tu API se verá en localhost:5000
    depends_on:
      - db # Espera a que la BD inicie primero
    environment:
      # Cadena de conexión apuntando al servicio 'db'
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=BuzonEscolarDB;User=sa;Password=TuPasswordFuerte123!;TrustServerCertificate=True;
    networks:
      - buzon-network

volumes:
  sql_data:

networks:
  buzon-network:

